### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by efposadac** [nubakery/bagel#60]
Dear all, 

I had to change a little bit some files to get the code compiled. I'm posting the changes here, maybe they are bugs, maybe not (this is my first time compiling the code). 

Cheers,

Fernando

==========

System:

Linux 4.0.2-1-ARCH
g++ (GCC) 4.9.2 20150304 
boost 1.58.0-1
cblas 3.5.0-2
lapack 3.5.0-1
blas 3.5.0-1

Compilation (Without optimization... to compile it faster):

autoreconf -ifv
./configure CFLAGS="-g" CXXFLAGS="-g" LIBS="-lblas -llapack -lcblas"
make

Changes:

```	diff
diff --git a/src/asd/dimer/dimer_cispace.h b/src/asd/dimer/dimer_cispace.h
index 715fd42..c5f7f5f 100644
--- a/src/asd/dimer/dimer_cispace.h
+++ b/src/asd/dimer/dimer_cispace.h
@@ -29,7 +29,7 @@
 #define __BAGEL_DIMER_CISPACE_H
 
 #include <utility>
-
+#include <set>
 #include <src/ci/fci/dvec.h>
 #include <src/ci/ras/civector.h>
 
diff --git a/src/ci/ras/sparse_ij.cc b/src/ci/ras/sparse_ij.cc
index 1f8ec66..d9b1aee 100644
--- a/src/ci/ras/sparse_ij.cc
+++ b/src/ci/ras/sparse_ij.cc
@@ -24,6 +24,7 @@
 //
 
 #include <src/ci/ras/sparse_ij.h>
+#include <src/wfn/reference.h>
 
 using namespace std;
 using namespace bagel;
diff --git a/src/util/serialization.h b/src/util/serialization.h
index 18a6388..d80d199 100644
--- a/src/util/serialization.h
+++ b/src/util/serialization.h
@@ -44,13 +44,13 @@
 #include <boost/serialization/nvp.hpp>
 #include <boost/serialization/complex.hpp>
 #include <boost/serialization/array.hpp>
-#include <boost/archive/shared_ptr_helper.hpp>
 #include <boost/property_tree/ptree_serialization.hpp>
-
 #if BOOST_VERSION >= 105600
 #include <boost/serialization/shared_ptr.hpp>
 #include <boost/serialization/weak_ptr.hpp>
 #include <boost/serialization/unordered_map.hpp>
+#else
+#include <boost/archive/shared_ptr_helper.hpp>
 #endif
 
 // to avoid duplicate serialize functions, we need to include this here
 ```

**Comment by shiozaki** [comment]
Thanks much - we have not tested 1.58.0, and unfortunately BOOST changes the API every release due to late digestion, which is a pain in the neck.

The first two look fine. Just to confirm - Have you checked if the third change (shared_ptr_helper.hpp) also works with 1.56.0 and 1.57.0 (which we have tested)? Or you just compiled with 1.58.0?

**Comment by shiozaki** [comment]
In addition, I am not sure why you need
```
#include <src/wfn/reference.h>
```
Could you let us see the error message without it? I don't find any objects that require this header.

**Comment by efposadac** [comment]
Prof. Shiozaki,

I compile the code with boost 1.57-03 and it worked. I can confirm that the problematic include in that version is at:

```
/usr/include/boost/archive/shared_ptr_helper.hpp
/usr/include/boost/serialization/shared_ptr_helper.hpp
```

This is the output without `#include <src/wfn/reference.h>` in file `a/src/ci/ras/sparse_ij.cc`: 

```make
/bin/sh ../../../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../../..    -I../../.. -std=c++11 -MT sparse_ij.lo -MD -MP -MF .deps/sparse_ij.Tpo -c -o sparse_ij.lo sparse_ij.cc
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../../.. -I../../.. -std=c++11 -MT sparse_ij.lo -MD -MP -MF .deps/sparse_ij.Tpo -c sparse_ij.cc  -fPIC -DPIC -o .libs/sparse_ij.o
sparse_ij.cc: In constructor ‘bagel::Sparse_IJ::Sparse_IJ(std::shared_ptr<const bagel::CIStringSet<bagel::RASString> >, std::shared_ptr<const bagel::CIStringSet<bagel::RASString> >)’:
sparse_ij.cc:47:12: error: ‘set’ was not declared in this scope
     vector<set<size_t>> sparse_set_vec(nsource);
            ^
sparse_ij.cc:47:16: error: template argument 1 is invalid
     vector<set<size_t>> sparse_set_vec(nsource);
                ^
sparse_ij.cc:47:16: error: template argument 2 is invalid
sparse_ij.cc:47:22: error: expected unqualified-id before ‘>’ token
     vector<set<size_t>> sparse_set_vec(nsource);
                      ^
sparse_ij.cc:61:15: error: ‘sparse_set_vec’ was not declared in this scope
               sparse_set_vec[isource_space].emplace(isrc + slen * itar);
               ^
sparse_ij.cc:75:15: error: ‘set’ does not name a type
         const set<size_t>& sparse_set = sparse_set_vec[isource_space];
               ^
sparse_ij.cc:77:31: error: ‘sparse_set’ was not declared in this scope
         sparse_coords.reserve(sparse_set.size());
                               ^
sparse_ij.cc:78:24: error: unable to deduce ‘auto&&’ from ‘sparse_set’
         for (auto& i : sparse_set)
                        ^
Makefile:452: recipe for target 'sparse_ij.lo' failed
make: *** [sparse_ij.lo] Error 1
```

It can be fixed as well by adding `#include <set>`... which I think would be nicer.

PD: I have some questions, may I contact you? how?

Cheers,

Fernando

**Comment by efposadac** [comment]
I have compiled using the boost 1.56 library...  With the proposed changes, the compilation was successfully.

**Comment by shiozaki** [comment]
thanks
